# modify this to adapt to your own environment
# change name to config.yaml to have effect

# Source data
DATA_DIR: ""
ALL_DATA: "/home/ubuntu/arx_prj/dataset/arxiv-metadata-oai-sample.gz"
DEV_SET: ""
TRAIN_SET: ""
VALIDATION_SET: ""
TEST_SET: ""

# index
INDEX_DIR: "se_index/"
INDEX_PREFIX: "sample"
CAT_ABBR_DICT: "res/cat_abbr_full.txt"
INDEX_CACHE_SIZE: 50
NUM_INDEX_FILES: 50
DOC_ID_2_DOC_NO: "res/DOC_ID_2_DOC_NO.json" # path to the mapping containing doc_id(str) to doc id (int)
DOC_ID_2_DOC_LEN: "res/DOC_ID_2_DOC_LEN.json" # path to the mapping containing doc_id(str) to doc length(int)

# search
SEARCH_RESULTS_KEEP: 500
SEARCH_RESULTS_PER_PAGE: 20
SEARCH_CACHE_SIZE: 50
BM25_COEFF: 1.5

# front end
CAT_SPLIT_SYMB: ","

# debug
DEBUG_PRINT: False