# modify this to adapt to your own environment
# change name to config.yaml to have effect

# Source data
DATA_DIR: ""
ALL_DATA: "arxiv-metadata-oai-sample.gz"
DEV_SET: ""
TRAIN_SET: ""
VALIDATION_SET: ""
TEST_SET: ""

# index
INDEX_DIR: ""
INDEX_PREFIX: ""
CAT_ABBR_DICT: "res/cat_abbr_full.txt"
INDEX_CACHE_SIZE: 50
NUM_INDEX_FILES: 1000
DOC_ID_2_DOC_NO: ".json" # path to the mapping containing doc_id(str) to doc id (int)
DOC_ID_2_DOC_LEN: ".json" # path to the mapping containing doc_id(str) to doc length(int)
RECORD_POSITION: False

# search
SEARCH_RESULTS_KEEP: 500
SEARCH_RESULTS_PER_PAGE: 20
SEARCH_CACHE_SIZE: 50
BM25_COEFF: 1.5

# Query suggestion
UNIGRAM_FILE: "res/unigram.json"
BIGRAM_FILE: "res/bigram.json"
TRIGRAM_FILE: "res/trigram.json"
ALL_NGRAMS_FILE: "res/all_ngrams.json"

# front end
CAT_SPLIT_SYMB: ","

# debug
DEBUG_PRINT: False

# Run
RUN_SERVER: False